imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    size_thumb: '400'
    size_medium: '2048'
    max_upload_size: 31457280
    allowed_extensions:
        - JPG
        - JPEG
        - GIF
        - PNG
        - BMP


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        signed_url_cacher: "@app.signed_url_cacher"
        breadcrumbs: "@breadcrumbs_organizer"
        default_form_theme: "foundation_5_layout.html.twig"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    port: "%mailer_port%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address:    noreply@visuari.com
        sender_name: Visuari
    registration:
        confirmation:
            enabled: true

oneup_flysystem:
    adapters:
        photoalbums_flysystem_adapter_local:
            local:
                directory: "%local_photo_directory%"
        photoalbums_flysystem_adapter:
            awss3v3:
                client: app.s3_client
                bucket: "%aws_s3_bucket%"
                prefix: ~
    filesystems:
        photoalbums:
            adapter: photoalbums_flysystem_adapter
            alias: photoalbums_filesystem
        photoalbums_local:
            adapter: photoalbums_flysystem_adapter_local
            alias: photoalbums_filesystem_local

oneup_uploader:
    mappings:
        photoalbums:
            frontend: dropzone
            storage:
                type: flysystem
                filesystem: photoalbums_filesystem
            max_size: %max_upload_size%
        photoalbums_local:
            frontend: dropzone
            storage:
                type: flysystem
                filesystem: photoalbums_filesystem_local
            max_size: %max_upload_size%

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

white_october_breadcrumbs:
    listClass: 'breadcrumbs'
    separator: ''