homepage:
    path: "/"
    defaults: { _controller: AppBundle:Default:index }
upload:
    path: "/upload"
    defaults: { _controller: AppBundle:Upload:upload }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
profile_base:
    resource: routing/profile_base.yml
    prefix: /{username}
    defaults: { username: "test"}
collection_base:
    resource: routing/collection_base.yml
    prefix: /collections