imports:
    - { resource: parameters.yml }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    imagine.handler:
        class: Imagine\Imagick\Imagine
    app.base_form:
        abstract: true
        arguments: ['@security.token_storage', '@translator']
    app.form.collection:
        class: AppBundle\Form\CollectionType
        parent: app.base_form
        tags:
            - { name: form.type }
    app.form.album:
        class: AppBundle\Form\AlbumType
        parent: app.base_form
        tags:
            - { name: form.type }
    app.form.upload_photos_to_album:
        class: AppBundle\Form\UploadPhotosToAlbumType
        parent: app.base_form
        tags:
            - { name: form.type }
    app.voter.collection:
        class: AppBundle\Security\CollectionVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    app.voter.album:
        class: AppBundle\Security\AlbumVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    app.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: 'latest' # '2012-10-17' # or 'latest'
                region: "us-east-1" # 'eu-central-1' for example
                credentials:
                    key: "%aws_s3_key%"
                    secret: "%aws_s3_secret%"
    app.upload_listener:
        class: AppBundle\EventListener\UploadListener
        arguments: ["@security.authorization_checker", "@doctrine.orm.entity_manager", "@translator", "@photoalbums_filesystem", "@photoalbums_filesystem_local", "@imagine.handler", %local_photo_directory%, %size_thumb%, %size_medium%, %allowed_extensions%]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }