# src/AppBundle/Resources/config/doctrine/Album.orm.yml

AppBundle\Entity\Album:
    type: entity
    table: album
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        create_date:
            type: datetime
            nullable: true
        change_date:
            type: datetime
            nullable: true
        description:
            type: text
            nullable: true
    manyToOne:
        collection:
            targetEntity: Collection
            joinColumn:
                referencedColumnName: id
        owner:
            targetEntity: User
            joinColumn:
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [setCreate_DateValue]
        preUpdate: [setChange_DateValue]