# src/AppBundle/Resources/config/doctrine/Album_Photo.orm.yml

AppBundle\Entity\Album_Photo:
    type: entity
    table: album_photo
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
            nullable: true
        title:
            type: string
            length: 255
            nullable: true
        caption:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
        change_date:
            type: datetime
            nullable: true
        description:
            type: text
            nullable: true
    manyToOne:
        photo:
            targetEntity: Photo
            joinColumn:
                referencedColumnName: id
        album:
            targetEntity: Album
            joinColumn:
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [setCreate_DateValue]
        preUpdate: [setChange_DateValue]