# src/AppBundle/Resources/config/doctrine/Permission.orm.yml

AppBundle\Entity\Permission:
    type: entity
    table: permission
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        level:
            type: integer
            default: 0
    manyToOne:
        collection:
            targetEntity: Collection
            joinColumn:
                referencedColumnName: id
        album:
            targetEntity: Album
            joinColumn:
                referencedColumnName: id
        album_photo:
            targetEntity: Album_Photo
            joinColumn:
                referencedColumnName: id
        grantee:
            targetEntity: User
            joinColumn:
                referencedColumnName: id
