# src/AppBundle/Resources/config/doctrine/User.orm.yml

AppBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        collections:
            targetEntity: Collection
            mappedBy: owner
    attributeOverride: # Change length of indexed fields from 255 to 191 so that the indexes will be within the MySQL index byte limit. This section is only used when creating (updating?) the database schema.
        usernameCanonical:
            name: username_canonical
            length: 191
            unique: true
        emailCanonical:
            name: email_canonical
            length: 191
            unique: true